server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:80
    gateway:
      routes:
        - id: user-service
          uri: lb://UserService
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://OrderService
          predicates:
            - Path=/order/**
            - Before=2037-01-20T15:14:47.443+08:00
      default-filters:
        - AddRequestHeader=Truth, Arecuid is my wife