server:
  port: 10086 # 服务端口
spring:
  application:
    name: eurekaserver #eureka的服务名称

eureka:
  client:
    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka #eureka注册的时候会把自己也注册上，作为集群的一员
      defaultZone: http://nacos:10086/eureka #eureka注册的时候会把自己也注册上，作为集群的一员